# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
cursor_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Dracula
# END_KITTY_THEME

# Colors
background #282A36
foreground #F8F8F2

# Cursor
cursor #F8F8F2
cursor_text_color #282A36

# Selection
selection_background #44475A
selection_foreground #F8F8F2

# URLs
url_color #BD93F9

# Tab bar
active_tab_background #343746
active_tab_foreground #F8F8F2
inactive_tab_background #282A36
inactive_tab_foreground #BFBFBF

# Marks
mark1_foreground #BD93F9
mark2_foreground #FF79C6
mark3_foreground #50FA7B

# ANSI colors
color0 #21222C
color1 #FF5555
color2 #50FA7B
color3 #F1FA8C
color4 #BD93F9
color5 #FF79C6
color6 #8BE9FD
color7 #F8F8F2
color8 #6272A4
color9 #FF6E6E
color10 #69FF94
color11 #FFFFA5
color12 #D6ACFF
color13 #FF92DF
color14 #A4FFFF
color15 #FFFFFF
