# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
cursor_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Rosé Pine
# END_KITTY_THEME

# Colors
background #191724
foreground #E0DEF4

# Cursor
cursor #E0DEF4
cursor_text_color #191724

# Selection
selection_background #26233A
selection_foreground #E0DEF4

# URLs
url_color #C4A7E7

# Tab bar
active_tab_background #1F1D2E
active_tab_foreground #E0DEF4
inactive_tab_background #191724
inactive_tab_foreground #908CAA

# Marks
mark1_foreground #C4A7E7
mark2_foreground #EBBCBA
mark3_foreground #9CCFD8

# ANSI colors
color0 #26233A
color1 #EB6F92
color2 #31748F
color3 #F6C177
color4 #9CCFD8
color5 #C4A7E7
color6 #EBBCBA
color7 #E0DEF4
color8 #6E6A86
color9 #EB6F92
color10 #31748F
color11 #F6C177
color12 #9CCFD8
color13 #C4A7E7
color14 #EBBCBA
color15 #E0DEF4
