# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
cursor_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Gruvbox
# END_KITTY_THEME

# Colors
background #282828
foreground #EBDBB2

# Cursor
cursor #EBDBB2
cursor_text_color #282828

# Selection
selection_background #3C3836
selection_foreground #EBDBB2

# URLs
url_color #D79921

# Tab bar
active_tab_background #32302F
active_tab_foreground #EBDBB2
inactive_tab_background #282828
inactive_tab_foreground #D5C4A1

# Marks
mark1_foreground #D79921
mark2_foreground #B8BB26
mark3_foreground #FE8019

# ANSI colors
color0 #3C3836
color1 #CC241D
color2 #98971A
color3 #D79921
color4 #458588
color5 #B16286
color6 #689D6A
color7 #EBDBB2
color8 #928374
color9 #FB4934
color10 #B8BB26
color11 #FABD2F
color12 #83A598
color13 #D3869B
color14 #8EC07C
color15 #EBDBB2
