# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
cursor_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Catppuccin
# END_KITTY_THEME

# Colors
background #24273A
foreground #CAD3F5

# Cursor
cursor #F4DBD6
cursor_text_color #24273A

# Selection
selection_background #494D64
selection_foreground #CAD3F5

# URLs
url_color #8AADF4

# Tab bar
active_tab_background #363A4F
active_tab_foreground #CAD3F5
inactive_tab_background #24273A
inactive_tab_foreground #A5ADCB

# Marks
mark1_foreground #8AADF4
mark2_foreground #A6DA95
mark3_foreground #F5BDE6

# ANSI colors
color0 #494D64
color1 #ED8796
color2 #A6DA95
color3 #EED49F
color4 #8AADF4
color5 #F5BDE6
color6 #8BD5CA
color7 #CAD3F5
color8 #5B6078
color9 #ED8796
color10 #A6DA95
color11 #EED49F
color12 #8AADF4
color13 #F5BDE6
color14 #8BD5CA
color15 #A5ADCB
