# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
cursor_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Gruvbox Light
# END_KITTY_THEME

# Colors
background #FBF1C7
foreground #3C3836

# Cursor
cursor #3C3836
cursor_text_color #FBF1C7

# Selection
selection_background #EBDBB2
selection_foreground #3C3836

# URLs
url_color #B57614

# Tab bar
active_tab_background #F2E5BC
active_tab_foreground #3C3836
inactive_tab_background #FBF1C7
inactive_tab_foreground #665C54

# Marks
mark1_foreground #B57614
mark2_foreground #79740E
mark3_foreground #D65D0E

# ANSI colors
color0 #EBDBB2
color1 #CC241D
color2 #79740E
color3 #B57614
color4 #458588
color5 #B16286
color6 #689D6A
color7 #3C3836
color8 #928374
color9 #9D0006
color10 #79740E
color11 #B57614
color12 #458588
color13 #B16286
color14 #689D6A
color15 #3C3836
