-- Generated by HyprMod

-- Settings
hl.config({
    general = {
        layout = "dwindle",
    },
    input = {
        natural_scroll = false,
        scroll_factor = 1.1,
    },
    misc = {
        vrr = 0,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Bezier curves
hl.curve("overshot", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("quick", { type = "bezier", points = { {0.15, 0.0}, {0.1, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10.0,
    bezier = "default",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "layers",
    enabled = false,
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})
hl.animation({
    leaf = "border",
    enabled = false,
})
hl.animation({
    leaf = "specialWorkspaceIn",
    enabled = true,
    speed = 3.8,
    bezier = "overshot",
    style = "slidefadevert",
})
hl.animation({
    leaf = "specialWorkspaceOut",
    enabled = true,
    speed = 3.8,
    bezier = "overshot",
    style = "slidevert",
})
hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 7.0,
    bezier = "quick",
})
