# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
cursor_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Nord
# END_KITTY_THEME

# Colors
background #2E3440
foreground #ECEFF4

# Cursor
cursor #ECEFF4
cursor_text_color #2E3440

# Selection
selection_background #434C5E
selection_foreground #ECEFF4

# URLs
url_color #88C0D0

# Tab bar
active_tab_background #3B4252
active_tab_foreground #ECEFF4
inactive_tab_background #2E3440
inactive_tab_foreground #D8DEE9

# Marks
mark1_foreground #88C0D0
mark2_foreground #A3BE8C
mark3_foreground #EBCB8B

# ANSI colors
color0 #3B4252
color1 #BF616A
color2 #A3BE8C
color3 #EBCB8B
color4 #81A1C1
color5 #B48EAD
color6 #88C0D0
color7 #E5E9F0
color8 #4C566A
color9 #BF616A
color10 #A3BE8C
color11 #EBCB8B
color12 #81A1C1
color13 #B48EAD
color14 #88C0D0
color15 #ECEFF4
