# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
cursor_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Everforest
# END_KITTY_THEME

# Colors
background #2B3339
foreground #D3C6AA

# Cursor
cursor #D3C6AA
cursor_text_color #2B3339

# Selection
selection_background #3A454A
selection_foreground #D3C6AA

# URLs
url_color #83C092

# Tab bar
active_tab_background #323C41
active_tab_foreground #D3C6AA
inactive_tab_background #2B3339
inactive_tab_foreground #A7C080

# Marks
mark1_foreground #83C092
mark2_foreground #E69875
mark3_foreground #7FBBB3

# ANSI colors
color0 #3A454A
color1 #E67474
color2 #A7C080
color3 #DBBC7F
color4 #7FBBB3
color5 #D699B6
color6 #83C092
color7 #D3C6AA
color8 #475258
color9 #E67474
color10 #A7C080
color11 #DBBC7F
color12 #7FBBB3
color13 #D699B6
color14 #83C092
color15 #D3C6AA
