# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
cursor_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Solarized
# END_KITTY_THEME

# Colors
background #002B36
foreground #EEE8D5

# Cursor
cursor #EEE8D5
cursor_text_color #002B36

# Selection
selection_background #0B3B49
selection_foreground #EEE8D5

# URLs
url_color #268BD2

# Tab bar
active_tab_background #073642
active_tab_foreground #EEE8D5
inactive_tab_background #002B36
inactive_tab_foreground #93A1A1

# Marks
mark1_foreground #268BD2
mark2_foreground #2AA198
mark3_foreground #B58900

# ANSI colors
color0 #073642
color1 #DC322F
color2 #859900
color3 #B58900
color4 #268BD2
color5 #D33682
color6 #2AA198
color7 #EEE8D5
color8 #002B36
color9 #CB4B16
color10 #586E75
color11 #657B83
color12 #839496
color13 #6C71C4
color14 #93A1A1
color15 #FDF6E3
