#################
### UNIVERSAL ###
#################
$body_font = 14
$huge_font = 70
$heading_font = 35
$large_font = 21
$small_font = 10
################
### TOP LEFT ###
################
$top_left_offset = -184, 99
$pw_box_offset = -184, 342
$un_box_offset = -184, 426
$pw_text_offset = 370, 384
$un_text_offset = 370, 468
$login_text_offset = -184, 524
$hostname_text_offset = -184, 594
$un_value_offset = 370, 447
$input_field_offset = 356, 342
$top_left_size = 341
$container_box_size = 285, 70
$input_field_size = 285, 56
###################
### BOTTOM LEFT ###
###################
$bottom_left_offset = -184, -184
$time_text_offset = -184, -511
$uptime_ltext_offset = 412, 143
$uptime_rtext_offset = -781, 143
$bottom_left_size = 170
#############
### RIGHT ###
#############
$right_offset = 184, 0
$right_bottom_box_offset = 184, 43
$network_box_offset = 105, 227
$bluetooth_box_offset = 261, 227
$power_box_offset = 184, 71
$image_offset = 184, 566
$media_symbol_offset = 184, -370
$network_symbol_offset = 105, 269
$bluetooth_symbol_offset = 261, 269
$day_value_offset = 184, 482
$date_value_offset = 184, 454
$media_content_value_offset = 184, -398
$media_player_value_offset = 184, -419
$network_value_offset = 105, 248
$bluetooth_value_offset = 261, 248
$power_status_value_offset = 184, 99
$power_percent_value_offset = 184, 113
$power_indicator_value_offset = 184, 155
$right_size = 341
$right_bottom_box_size = 341, 383
$power_box_size = 285, 127
$connection_box_size = 127, 85
$image_size = 113
