font_family JetBrains Mono Nerd Font
font_size 14.0

cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
curso_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3


confirm_os_window_close 0

shell zsh

map ctrl+c    copy_or_interrupt

map page_up    scroll_page_up
map page_down    scroll_page_down
map ctrl+shift+s new_window
map ctrl+equal  change_font_size all +1
map ctrl+minus  change_font_size all -1
map alt+shift+l next_window
map alt+shift+h previous_window

include current-theme.conf
