# Font
font_family      JetBrains Mono Nerd Font
font_size 11.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
curso_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# Padding (why weird value? consistency with foot)

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Search

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
