# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
cursor_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Monochrome
# END_KITTY_THEME

# Colors
background #000000
foreground #E5E7EB

# Cursor
cursor #E5E7EB
cursor_text_color #000000

# Selection
selection_background #303030
selection_foreground #E5E7EB

# URLs
url_color #9CA3AF

# Tab bar
active_tab_background #1A1A1A
active_tab_foreground #E5E7EB
inactive_tab_background #000000
inactive_tab_foreground #9CA3AF

# Marks
mark1_foreground #E5E7EB
mark2_foreground #9CA3AF
mark3_foreground #6B7280

# ANSI colors
color0 #000000
color1 #E5E7EB
color2 #9CA3AF
color3 #6B7280
color4 #E5E7EB
color5 #9CA3AF
color6 #6B7280
color7 #E5E7EB
color8 #1A1A1A
color9 #E5E7EB
color10 #9CA3AF
color11 #6B7280
color12 #E5E7EB
color13 #9CA3AF
color14 #6B7280
color15 #FFFFFF
