# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_trail 3
cursor_shape block
shell_integration disabled
disable_ligatures yes
background_opacity 0.8
initial_window_width 80c
initial_window_height 25c
cursor_blink_interval 0

sync_to_monitor no
repaint_delay 8
input_delay 3

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell zsh

# Copy
map ctrl+c    copy_or_interrupt

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus  change_font_size all +1
map ctrl+equal  change_font_size all +1
map ctrl+minus       change_font_size all -1

# BEGIN_KITTY_THEME
# Catppuccin Latte
# END_KITTY_THEME

# Colors
background #EFF1F5
foreground #4C4F69

# Cursor
cursor #DC8A78
cursor_text_color #EFF1F5

# Selection
selection_background #DCE0E8
selection_foreground #4C4F69

# URLs
url_color #1E66F5

# Tab bar
active_tab_background #E6E9EF
active_tab_foreground #4C4F69
inactive_tab_background #EFF1F5
inactive_tab_foreground #6C6F85

# Marks
mark1_foreground #1E66F5
mark2_foreground #40A02B
mark3_foreground #EA76CB

# ANSI colors
color0 #DCE0E8
color1 #D20F39
color2 #40A02B
color3 #DF8E1D
color4 #1E66F5
color5 #EA76CB
color6 #179299
color7 #4C4F69
color8 #CCD0DA
color9 #D20F39
color10 #40A02B
color11 #DF8E1D
color12 #1E66F5
color13 #EA76CB
color14 #179299
color15 #5C5F77
